import { AreaChart,Area,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,Cell,ReferenceLine,LineChart,Line,ScatterChart,Scatter,ZAxis } from 'recharts';
import { money,num,date } from './lib';
const axis={fontSize:12,fill:'#91988d'};
function Tip({active,payload,label,percent=false}:{active?:boolean;payload?:any[];label?:any;percent?:boolean}){return active&&payload?.length?<div className="chart-tip"><span>{label}</span>{payload.filter(p=>p.value!=null).map((p,i)=><strong key={i} style={{color:p.color}}>{p.name}: {percent?num(p.value)+'%':money(p.value)}</strong>)}</div>:null;}
export function EquityChart({data,drawdown=false,height=255}:{data:any[];drawdown?:boolean;height?:number}){return <ResponsiveContainer width="100%" height={height}><AreaChart data={data} margin={{top:12,right:14,bottom:0,left:0}}><defs><linearGradient id={drawdown?'redGradient':'greenGradient'} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={drawdown?'#d1867f':'#bddb91'} stopOpacity={.4}/><stop offset="100%" stopColor={drawdown?'#d1867f':'#bddb91'} stopOpacity={.01}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e9ede6"/><XAxis dataKey="date" tick={axis} axisLine={false} tickLine={false} minTickGap={55} tickFormatter={v=>v==='Start'?'Start':date(v)}/><YAxis tick={axis} axisLine={false} tickLine={false} width={64} tickFormatter={v=>money(v,true)}/><Tooltip content={<Tip/>}/><ReferenceLine y={0} stroke="#dfe4da"/><Area type="monotone" dataKey={drawdown?'drawdown':'pnl'} name={drawdown?'Drawdown':'Net P&L'} stroke={drawdown?'#c96962':'#81a954'} strokeWidth={2.3} fill={`url(#${drawdown?'redGradient':'greenGradient'})`} activeDot={{r:5,strokeWidth:3,stroke:'#fff'}}/></AreaChart></ResponsiveContainer>;}
export function GroupChart({data,metric='net_pnl',height=240,horizontal=false}:{data:any[];metric?:string;height?:number;horizontal?:boolean}){
  return <ResponsiveContainer width="100%" height={height}><BarChart data={data} layout={horizontal?'vertical':'horizontal'} margin={{top:8,right:12,left:horizontal?12:0,bottom:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e9ede6"/>{horizontal?<><XAxis type="number" tick={axis} axisLine={false} tickLine={false}/><YAxis dataKey="name" type="category" width={115} tick={axis} axisLine={false} tickLine={false}/></>:<><XAxis dataKey={data[0]?.date?'date':'name'} tick={axis} axisLine={false} tickLine={false} minTickGap={20} tickFormatter={v=>data[0]?.date?date(v):v}/><YAxis tick={axis} axisLine={false} tickLine={false} width={55} tickFormatter={v=>metric==='net_pnl'?money(v,true):num(v)}/></>}<Tooltip cursor={{fill:'#f2f5ee'}} formatter={(v:any)=>metric.includes('pnl')||metric==='fees'?money(Number(v)):num(Number(v))}/><ReferenceLine y={horizontal?undefined:0} x={horizontal?0:undefined} stroke="#dfe4da"/><Bar dataKey={metric} name={metric.replaceAll('_',' ')} radius={horizontal?[0,4,4,0]:[4,4,0,0]} maxBarSize={32}>{data.map((r,i)=><Cell key={i} fill={r[metric]>=0?'#a4c77d':'#dfa59b'}/>)}</Bar></BarChart></ResponsiveContainer>;
}
export function ExcursionChart({data}:{data:any[]}){return <ResponsiveContainer width="100%" height={260}><ScatterChart margin={{right:20,left:12,top:15,bottom:20}}><CartesianGrid strokeDasharray="3 5" stroke="#e9ede6"/><XAxis dataKey="mfe" type="number" name="MFE" tick={axis} label={{value:'MFE (supplied currency value)',position:'bottom',fontSize:12}}/><YAxis dataKey="net_pnl" name="Net P&L" tick={axis}/><Tooltip cursor={{strokeDasharray:'3 3'}}/><Scatter data={data.filter(t=>t.mfe!=null)} fill="#91b964"/></ScatterChart></ResponsiveContainer>;}
export function Candles({candles,position,indicator='sma',timeframe=1,onPricePick}:{candles:any[];position:any;indicator?:string;timeframe?:number;onPricePick?:(value:number)=>void}){
  const aggregated:any[]=[];
  for(let i=0;i<candles.length;i+=timeframe){const slice=candles.slice(i,i+timeframe);aggregated.push({...slice[0],high:Math.max(...slice.map(c=>c.high)),low:Math.min(...slice.map(c=>c.low)),close:slice.at(-1).close});}
  const data=aggregated.slice(-90),width=920,height=350,pad=40;
  if(!data.length)return null;
  const prices=data.flatMap(c=>[c.high,c.low]).concat(position?[position.entry_price,position.stop_loss,position.target_price].filter(x=>x!=null):[]);
  const lo=Math.min(...prices)*.998,hi=Math.max(...prices)*1.002;
  const y=(n:number)=>height-pad-(n-lo)/(hi-lo||1)*(height-pad*2);
  const x=(i:number)=>pad+i/(data.length||1)*(width-pad*2)+4;
  const bar=Math.max(2,Math.min(10,(width-pad*2)/data.length*.65));
  const sma=data.map((_,i)=>({i,value:data.slice(Math.max(0,i-19),i+1).reduce((s,c)=>s+c.close,0)/Math.min(i+1,20)}));
  return <svg className="candles" style={{cursor:onPricePick?'crosshair':undefined}} viewBox={`0 0 ${width} ${height}`} onClick={e=>{if(!onPricePick)return;const rect=e.currentTarget.getBoundingClientRect();const py=(e.clientY-rect.top)/rect.height*height;onPricePick(lo+(height-pad-py)/(height-pad*2)*(hi-lo));}} role="img" aria-label="Historical candle replay showing revealed bars only">{Array.from({length:6},(_,i)=>{const price=lo+(hi-lo)*i/5;return <g key={i}><line x1={pad} x2={width-pad} y1={y(price)} y2={y(price)} stroke="#283029" strokeDasharray="4 5"/><text x={width-pad+6} y={y(price)+4} fill="#879287" fontSize="11">{price.toFixed(2)}</text></g>;})}{data.map((c,i)=><g key={i}><title>{date(c.time,{hour:'2-digit',minute:'2-digit'})} O:{c.open} H:{c.high} L:{c.low} C:{c.close}</title><line x1={x(i)} x2={x(i)} y1={y(c.high)} y2={y(c.low)} stroke={c.close>=c.open?'#b7e58b':'#d18d82'}/><rect x={x(i)-bar/2} y={Math.min(y(c.open),y(c.close))} width={bar} height={Math.max(1,Math.abs(y(c.open)-y(c.close)))} fill={c.close>=c.open?'#b7e58b':'#d18d82'}/></g>)}{indicator==='sma'&&<polyline points={sma.map(d=>`${x(d.i)},${y(d.value)}`).join(' ')} fill="none" stroke="#d9ba79" strokeWidth="1.5"/>}{position&&[['Entry',position.entry_price,'#8ba9d8'],['Stop',position.stop_loss,'#d18d82'],['Target',position.target_price,'#b7e58b']].map(([label,value,color])=>value!=null&&<g key={String(label)}><line x1={pad} x2={width-pad} y1={y(Number(value))} y2={y(Number(value))} stroke={String(color)} strokeDasharray="5 5"/><text x={pad+4} y={y(Number(value))-5} fill={String(color)} fontSize="12">{label} {num(Number(value),4)}</text></g>)}<text x={pad} y={height-8} fill="#879287" fontSize="11">{date(data[0].time,{hour:'2-digit',minute:'2-digit'})}</text><text x={width-pad-130} y={height-8} fill="#879287" fontSize="11">{date(data.at(-1).time,{hour:'2-digit',minute:'2-digit'})}</text></svg>;
}
