import { useEffect, useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, Crosshair, Layers3, Menu, Minus, MoveUpRight, Plus, Sparkles, X } from 'lucide-react';
import { Pricing } from './Pricing';
import { Select } from './Select';
import type { Catalog } from './types';
import './landing.css';

const demos = [
  {id:'nifty', name:'NIFTY · Index options', symbol:'NIFTY', subtitle:'Opening range breakout', date:'09:25 IST', r:'+2.4R', pnl:'+₹3,600', note:'Waited for the retest. Kept the stop where the setup failed.', lesson:'The entry was patient. Keep that part.', values:[40,44,37,49,46,54,45,40,48,60,55,63,59,73,67,81,77,87,79,91,86,98,91,105,98,113,107,117,110,124]},
  {id:'equity', name:'RELIANCE · NSE equity', symbol:'RELIANCE', subtitle:'Breakout without confirmation', date:'11:10 IST', r:'−1.0R', pnl:'−₹1,500', note:'Entered before the candle closed. Exited at the planned stop.', lesson:'Good risk control. Give the next entry time to confirm.', values:[75,78,70,82,77,88,82,95,100,91,96,89,97,83,80,86,71,77,68,74,60,65,54,61,50,58,49,44,51,40]},
  {id:'crypto', name:'BTC · Crypto', symbol:'BTC', subtitle:'Range reclaim', date:'19:40 IST', r:'+1.8R', pnl:'+₹2,700', note:'Scaled out at the range midpoint. Left the rest to the plan.', lesson:'You managed the position before managing the emotion.', values:[88,80,83,68,73,63,71,62,75,82,76,89,84,95,88,101,93,105,99,113,106,118,110,120,115,126,119,130,122,134]},
];
function CandleChart({values,active,onActive}:{values:number[];active:number;onActive:(n:number)=>void}) {
  const y = (value:number) => 176 - (value - 25) * 1.13;
  return <svg className="sample-chart" viewBox="0 0 480 205" role="img" aria-label="Illustrative price candles. Use the slider below to explore the example." onPointerMove={e => {const rect = e.currentTarget.getBoundingClientRect(); onActive(Math.min(values.length - 1, Math.max(0, Math.floor((e.clientX - rect.left) / rect.width * values.length))));}}>
    {[35,80,125,170].map(v => <line key={v} x1="0" x2="480" y1={v} y2={v} stroke="#354336" strokeDasharray="3 5"/>)}
    <path d={'M '+values.map((v,i) => `${10+i*15.7},${y(v)+15}`).join(' L ')} fill="none" stroke="#829e5c" strokeWidth="1" opacity=".4"/>
    {values.map((v,i) => {const previous = values[Math.max(0,i-1)]-2, positive = v >= previous, x = 10+i*15.7; return <g key={i} opacity={i <= active ? 1 : .27}><line x1={x} x2={x} y1={y(Math.max(v,previous)+5)} y2={y(Math.min(v,previous)-5)} stroke={positive?'#c2e999':'#bd8977'}/><rect x={x-3.5} y={y(Math.max(v,previous))} width="7" height={Math.max(3,Math.abs(v-previous)*1.13)} rx="1" fill={positive?'#c2e999':'#bd8977'}/></g>;})}
    <line x1={10+active*15.7} x2={10+active*15.7} y1="15" y2="177" stroke="#d6ebba" strokeDasharray="3 4" opacity=".6"/>
    <text x="0" y="202" fill="#81917a" fontSize="9">ENTRY</text><text x="216" y="202" fill="#81917a" fontSize="9">THE PROCESS</text><text x="455" y="202" fill="#81917a" fontSize="9">EXIT</text>
  </svg>;
}
function JournalPreview() {
  const [market,setMarket] = useState('nifty'), [active,setActive] = useState(22);
  const demo = demos.find(d => d.id === market)!;
  return <div className="journal-scene" onPointerMove={e => {if (window.matchMedia('(prefers-reduced-motion: reduce), (pointer: coarse)').matches) return; const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--rx',`${(e.clientY-r.top-r.height/2)/150}deg`);e.currentTarget.style.setProperty('--ry',`${(e.clientX-r.left-r.width/2)/140}deg`);}} onPointerLeave={e => {e.currentTarget.style.setProperty('--rx','0deg');e.currentTarget.style.setProperty('--ry','0deg');}}>
    <div className="scene-grid"/><span className="scene-caption">A LITTLE DISTANCE. A LOT MORE CLARITY.</span>
    <div className="journal-preview"><div className="preview-top"><span className="preview-mark">H</span><span>THE SESSION, REVISITED</span><span className="preview-example">INTERACTIVE EXAMPLE</span></div>
      <div className="preview-body"><div className="preview-toolbar"><Select aria-label="Explore an example market" value={market} onChange={e => {setMarket(e.target.value);setActive(22);}}>{demos.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</Select><span className="preview-time">{demo.date}</span></div>
      <div className="preview-heading"><div><h3>{demo.symbol}<span> / JOURNAL</span></h3><p>{demo.subtitle}</p></div><strong className={demo.id==='equity'?'sample-loss':''}>{demo.r}</strong></div>
      <CandleChart values={demo.values} active={active} onActive={setActive}/><label className="chart-scrubber"><span>Drag to revisit the trade</span><input aria-label="Explore example candles" type="range" min="0" max="29" value={active} onChange={e => setActive(Number(e.target.value))}/><span>{String(active+1).padStart(2,'0')} / 30</span></label>
      <div className="preview-note"><BookOpen size={15}/><div><span>YOUR POST-TRADE NOTE</span><p>{demo.note}</p></div></div></div>
      <div className="preview-bottom"><span><span/>Plan documented</span><span>Risk reviewed <Check size={12}/></span></div>
    </div>
    <div className="lesson-card"><span className="lesson-icon"><Sparkles size={18}/></span><div><span>THE TAKEAWAY</span><p>{demo.lesson}</p></div></div>
    <div className="scene-stamp"><MoveUpRight size={19}/><span>REFLECT.<br/>REFINE.<br/>REPEAT.</span></div>
    <p className="demo-disclosure">Illustrative trades and insights. Not live market data.</p>
  </div>;
}
const chapters = [
  {title:'Capture the whole trade.',text:'The entry. The exit. The hesitation in between. Keep your execution, setup and state of mind together.',tab:'Record',icon:BookOpen,tag:'01 / THE CONTEXT',heading:'A number tells you what.\nA journal tells you why.',rows:[['Setup','Opening range breakout'],['State of mind','Focused, not chasing'],['Risk plan','Defined before entry']],note:'“Skipped the first move. Took the retest I had planned.”'},
  {title:'Find what keeps repeating.',text:'Review your setups, risk and habits. Ask AI questions grounded in your own journal, and follow the evidence back to your trades.',tab:'Review',icon:Crosshair,tag:'02 / THE PATTERN',heading:'Your best question starts\nwith your own history.',rows:[['Ask your journal','Which setups am I rushing?'],['Look closer','Entry timing · Notes · Outcomes'],['Stay grounded','Review the supporting trades']],note:'“Show me the trades where I broke my entry rules.”'},
  {title:'Give tomorrow a better plan.',text:'Write the rule you want to follow. Save the playbook. Use market replay to practise your decision before another session begins.',tab:'Refine',icon:Layers3,tag:'03 / THE NEXT SESSION',heading:'One useful lesson.\nOne more deliberate session.',rows:[['Keep','Waiting for a retest'],['Change','Moving the stop mid-trade'],['Practise','The same setup in market replay']],note:'“Tomorrow: confirmation first. Position second.”'},
];
function Workflow() {
  const [chapter,setChapter] = useState(0), current=chapters[chapter];
  return <section className="workflow-section" id="how-it-works"><div className="landing-container workflow-layout"><div className="workflow-copy"><span className="section-kicker">CLOSE THE TRADE. OPEN THE JOURNAL.</span><h2>A better routine.<br/><em>Trade by trade.</em></h2><div className="workflow-steps">{chapters.map((step,i) => <button type="button" key={step.tab} aria-pressed={chapter===i} onClick={() => setChapter(i)} className={chapter===i?'selected':''}><span className="step-index">0{i+1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div><ArrowUpRight size={18}/></button>)}</div></div><div className="workflow-paper"><div className="paper-top"><span>THE TRADER’S FIELD NOTES</span><span>{String(chapter+1).padStart(2,'0')} — 03</span></div><div className="paper-content" key={chapter}><current.icon size={33} strokeWidth={1.3}/><span className="paper-tag">{current.tag}</span><h3>{current.heading.split('\n').map((line,i)=><span key={i}>{line}</span>)}</h3><div className="paper-rows">{current.rows.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><blockquote>{current.note}</blockquote></div><div className="paper-bottom"><span>ILLUSTRATIVE WORKFLOW</span><span className="paper-signature">HakiSense</span></div></div></div></section>;
}

export default function Landing() {
  const {pathname,hash,key:locationKey} = useLocation(), pricingOnly = pathname === '/pricing';
  const [catalog,setCatalog] = useState<Catalog|null>(null), [error,setError] = useState(false), [retry,setRetry] = useState(0), [mobile,setMobile] = useState(false);
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {const controller=new AbortController();setError(false);fetch('/api/catalog',{signal:controller.signal}).then(r => {if(!r.ok) throw new Error();return r.json();}).then(setCatalog).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>controller.abort();},[retry]);
  useEffect(() => {setMobile(false);if(hash)requestAnimationFrame(()=>document.getElementById(decodeURIComponent(hash.slice(1)))?.scrollIntoView());else window.scrollTo(0,0);document.title=pricingOnly?'Credit packs & pricing · HakiSense':'HakiSense — Your next edge is in your last trade';},[pathname,hash,pricingOnly,locationKey]);
  useEffect(() => {let frame=0;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{frame=0;root.current?.style.setProperty('--scroll-drift',`${reduced.matches?0:Math.min(window.scrollY,850)*.09}px`);};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};window.addEventListener('scroll',scroll,{passive:true});reduced.addEventListener('change',scroll);return()=>{window.removeEventListener('scroll',scroll);reduced.removeEventListener('change',scroll);cancelAnimationFrame(frame);};},[]);
  const faqs=[
    ['Can I use it for free?',`Yes. All existing journal tools, replay and unlimited trade entries are available without a subscription. You receive ${catalog?.monthly_free_credits??'monthly free'} credits${catalog?' every month':''}. No card needed.`],
    ['What uses credits?',`AI tasks show their cost before you run them. Creating a playbook costs ${catalog?.playbook_creation_credits??1} credit(s). Editing playbooks and logging trades are free.`],
    ['Do my credits expire?',catalog?.credit_policy||'Purchased credits do not expire. Monthly free credits refresh in IST. Failed AI tasks are refunded.'],
    ['Can everyone use Advanced AI?',`Yes. Choose Standard or Advanced in the AI coach. Advanced requests cost ${catalog?.advanced_credit_multiplier??3}× the Standard task price. Deep Researched Stock Analysis is still in development and not available yet.`],
    ['Will I be charged every month?','No. Recharges are one-time purchases. There is no automatic renewal or monthly commitment. Buy another pack only when you need it.'],
  ];
  return <div ref={root} className={`landing ${pricingOnly?'pricing-page':''}`}><a className="landing-skip" href="#landing-main">Skip to content</a><header className="landing-header"><div className="landing-container landing-nav"><Link to="/" className="landing-brand"><span className="brand-logo">H</span><span>{catalog?.brand_name || 'HakiSense'}<small>THE TRADING JOURNAL</small></span></Link><nav className={mobile?'open':''} aria-label="Main navigation"><Link to="/#how-it-works" onClick={()=>setMobile(false)}>The process</Link><Link to="/#made-for-india" onClick={()=>setMobile(false)}>Built for India</Link><Link to="/help">Help</Link><Link className={pricingOnly?'active':''} to="/pricing">Pricing</Link></nav><div className="landing-nav-actions"><Link className="landing-login" to="/login">Sign in</Link><Link className="landing-start" to="/signup">Start journaling <ArrowUpRight size={16}/></Link><button className="landing-mobile-toggle" type="button" aria-label={mobile?'Close navigation':'Open navigation'} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X size={21}/>:<Menu size={21}/>}</button></div></div></header>
    <main className="landing-main" id="landing-main">{!pricingOnly && <><section className="landing-container landing-hero"><div className="hero-copy"><div className="hero-kicker"><span/>FOR THE TRADER BEHIND THE TRADE</div><h1>Your next edge<br/>is in your<br/><em>last trade.</em><span className="hero-period">↗</span></h1><p>The market moves on. The lesson shouldn’t.<br/>A thoughtful trading journal for Indian markets, your decisions, and the patterns in between.</p><div className="hero-actions"><Link className="landing-cta" to="/signup">Make your first entry <ArrowUpRight size={19}/></Link><a className="hero-secondary" href="#how-it-works">Take a closer look <ArrowDown size={15}/></a></div><div className="hero-footnote"><span className="tiny-check"><Check size={11}/></span>Free to start<span>·</span>No card needed<span>·</span>Built around you</div></div><JournalPreview/><div className="hero-bottom"><span>01 — A CLEARER PERSPECTIVE</span><span>YOUR TRADES HAVE SOMETHING TO TELL YOU <ArrowDown size={12}/></span></div></section>
    <section className="market-strip" aria-label="Markets supported"><div className="landing-container"><span>YOUR MARKETS.<br/><strong>YOUR HOME TURF.</strong></span><div>NIFTY <small>50</small></div><div>BANKNIFTY</div><div>NSE <span>/</span> BSE</div><div>BTC <span>/</span> ETH</div><div className="market-strip-meta">₹ INR REPORTING<br/>IST, ALWAYS</div></div></section>
    <Workflow/>
    <section className="landing-container india-section" id="made-for-india"><div className="india-heading"><span className="section-kicker">HOME ADVANTAGE</span><h2>From Dalal Street<br/>to your <em>desk.</em></h2><p>Your market has its own rhythm.<br/>Your journal should understand it.</p><Link to="/signup" className="inline-arrow">Find your rhythm <ArrowUpRight size={17}/></Link></div><div className="india-features"><article><span className="india-symbol">₹</span><div><h3>Your performance, in rupees.</h3><p>Your performance, fees and risk in INR. Your sessions and calendar in Indian Standard Time.</p></div><span className="india-number">01</span></article><article><span className="india-symbol"><Layers3 size={27} strokeWidth={1.4}/></span><div><h3>One journal. Your markets.</h3><p>Index options, futures, NSE & BSE equities and crypto. Keep the context behind every position.</p></div><span className="india-number">02</span></article><article><span className="india-symbol"><BookOpen size={26} strokeWidth={1.4}/></span><div><h3>Bring your trading history.</h3><p>Add a trade by hand or import your broker’s file. Keep your accounts organised and your notes close.</p></div><span className="india-number">03</span></article></div></section></>}
    <div className="landing-pricing-wrap"><div className="landing-container">{pricingOnly&&<div className="pricing-page-intro"><span>THE SPACE TO TAKE YOUR PROCESS SERIOUSLY.</span><Link to="/">Back to HakiSense <ArrowUpRight size={14}/></Link></div>}{catalog?<Pricing catalog={catalog} headingLevel={pricingOnly?1:2}/>:<div className="catalog-state" role="status"><h2>{error?'The packs are taking a moment.':'Credits for your next question.'}</h2><p>{error?'We couldn’t load current pricing. Please try again.':'Loading current prices and allowances…'}</p>{error&&<button type="button" className="landing-start" onClick={()=>setRetry(n=>n+1)}>Try again</button>}</div>}</div></div>
    <section className="landing-container faq-section"><div><span className="section-kicker">BEFORE YOUR FIRST ENTRY</span><h2>A few things<br/>you might ask.</h2></div><div className="faq-list">{faqs.map(([question,answer])=><details key={question}><summary>{question}<Plus size={16}/><Minus size={16}/></summary><p>{answer}</p></details>)}</div></section>
    <section className="landing-container last-entry"><div className="last-entry-mark">H</div><span className="section-kicker">THE MARKET OPENS AGAIN. SO DOES YOUR JOURNAL.</span><h2>Make the next session<br/><em>a little more deliberate.</em></h2><Link className="landing-cta" to="/signup">Start your free journal <ArrowUpRight size={19}/></Link><p>No perfect trades required. Just an honest first entry.</p></section></main>
    <footer className="landing-footer"><div className="landing-container"><div className="footer-top"><Link className="landing-brand" to="/"><span className="brand-logo">H</span><span>{catalog?.brand_name || 'HakiSense'}<small>REFLECT. REFINE. REPEAT.</small></span></Link><p>For the work that happens<br/>after the trade.</p><div><Link to="/pricing">Pricing</Link><Link to="/help">Help & customer care</Link><Link to="/login">Sign in</Link>{catalog?.legal.support_email&&<a href={'mailto:'+catalog.legal.support_email}>Get in touch</a>}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {catalog?.brand_name || 'HakiSense'} · Made for Indian traders</span><div>{catalog?.legal.terms&&<a href={catalog.legal.terms}>Terms</a>}{catalog?.legal.privacy&&<a href={catalog.legal.privacy}>Privacy</a>}{catalog?.legal.refunds&&<a href={catalog.legal.refunds}>Refunds</a>}<span>INR / IST</span></div></div></div></footer>
  </div>;
}
