import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/space-grotesk/500.css';
import '@fontsource/space-grotesk/600.css';
import { App } from './App';
import './styles.css';
import './pages.css';
import './admin.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
